---
- name: Basic configuration for all servers
  hosts: all
  gather_facts: false   # ✅ Use `false` instead of `no`
  connection: local
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: ~/.ssh
        mode: '0700'
        state: directory

    - name: Ensure known_hosts file exists
      ansible.builtin.copy:
        content: ""
        dest: ~/.ssh/known_hosts
        mode: '0600'

    - name: Check if known_hosts contains server's fingerprint
      ansible.builtin.command: ssh-keygen -F {{ inventory_hostname }}
      register: keygen
      failed_when: keygen.stderr != ''
      changed_when: false  # ✅ Use `false`

    - name: Fetch remote ssh key
      ansible.builtin.command: ssh-keyscan -T5 {{ inventory_hostname }}
      register: keyscan
      failed_when: keyscan.rc != 0 or keyscan.stdout == ''
      changed_when: false  # ✅ Use `false`
      when: keygen.rc == 1

    - name: Add ssh-key to local known_hosts
      ansible.builtin.lineinfile:
        path: ~/.ssh/known_hosts
        create: true  # ✅ Use `true`
        line: "{{ item }}"
        mode: '0600'
      when: keygen.rc == 1
      loop: "{{ keyscan.stdout_lines | default([]) }}"

- name: Ensure Apache is installed with the correct modules
  hosts: web-servers
  become: true
  tasks:
    - name: Ensure Apt is up to date
      ansible.builtin.apt:
        update_cache: true  # ✅ Use `true`

    - name: Ensure Apache is installed
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Ensure PHP is installed
      ansible.builtin.apt:
        name: php8.3
        state: present
    nosense
    - name: Ensure PHP Module for Apache is installed
      ansible.builtin.apt:
        name: libapache2-mod-php8.3
        state: present

    - name: Ensure MySQL for Apache is installed
      ansible.builtin.apt:
        name: php8.3-mysql
        state: present

- name: Deploy the application-package
  hosts: web-servers
  become: true
  tasks:
    - name: Install PHP File
      ansible.builtin.copy:
        src: files/index.php
        dest: /var/www/html/index.php
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure default HTML file does not exist
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
