name: LAMP Deployment

on:
    workflow_dispatch:

jobs:
  linting:
    name: Lint Ansible files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Linting
      uses: ansible/ansible-lint-action@49ded6a7e4f3acf6b1eb4b3aa2796d84b5faa63a
      with:
        tergets:
          ansible/playbook.yml
          ansible/inventory.yml
          
